# Generated by Django 5.2 on 2025-05-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="name",
        ),
    ]
